---
title: "raster-functions"
author: "Leah A. Wasser"
date: "June 21, 2016"
output: html_document
---

```{r import}
# load libraries

library(raster)
library(rgdal)

chm <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarCHM.tif")

plot(chm)
chm[chm==0] <- NA
density(chm)

height.class.m <- c(0, 6, 1,
                    6, 30, 2,
                    30, 50, 3,
                    50, 100, 4)

height.class.mat <- matrix(height.class.m,
                         ncol=3,
                         byrow=TRUE)

height.class.mat

reclassified.chm <- reclassify(chm,
                               height.class.mat)
reclassified.chm
density(chm,
        main="Canopy height density",
        xlab = "height (m)")

# sapply(reclass.height.mat[,2], function(x) abline(v = x, col = "red"))
abline(v = height.class.mat[,2], col="red")

# pdf output
pdf(file = "TEAK-chm-density.pdf", width = 6, height = 7)
density(chm,
        main="Canopy height density",
        xlab = "height (m)")
abline(v = height.class.mat[,2], col="red")
dev.off()

```

```{r plot-graphics }

# margins - bottom left up right
par(xpd = FALSE, 
    mar = c(5.1, 4.1, 4.1, 4.5))


plot(reclassified.chm,
      col = c("yellow", "springgreen", "green", "blue"),
      main="Canopy Height",
      axes=F,
      legend=FALSE,
      box=FALSE)

plot(extent(reclassified.chm), 
     add=T,
     lwd=3)

par(xpd = TRUE)

# legend position
leg.x <- par()$usr[2] + 20
leg.y <- par()$usr[4] + 50 - (abs(par()$usr[3] - par()$usr[4]) / 2)


# add legend
legend(leg.x, leg.y,
       legend = c("0-6m", "6-30", "30-50", "50-100"),
       fill=c("yellow", "springgreen", "green", "blue"),
       bty = "n") # turn off legend border


# general log file of processing

sink(paste0(format(Sys.time(), "%Y-%m-%d_%H%M%S"), 
            "_sessionInfo.txt"))
sessionInfo()
sink()

```


```{r hist-info }

# create histogram object
# histinfo <- hist(chm, breaks=c(0, 6, 30, 50, 100))

# create histogram breaks object
the.breaks <- c(0, 6, 30, 50, 100)

# function that creates a breaks matrix
class.num <- length(the.breaks)-1
m = matrix(0, # initialize the matrix with 0's
           class.num, # total classes to create
           3) # create a 3 column matrix
# init vector
test <- 1:class.num

# here are some changes

# of breaks in our matrix
for(i in (1:class.num)){
  m[i,] <- c(the.breaks[i], the.breaks[i+1], i)
  test[i] <- paste0(the.breaks[i],"-",the.breaks[i+1])
}

# create list of labels
class.num

```

